# Generated by Django 2.1.7 on 2019-05-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('post', '0002_auto_20190512_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['by'], name='comment_by_id_6c8945_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='Post_user_id_6ffe10_idx'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='like',
            table='Like',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
