# Generated by Django 2.1.7 on 2019-05-12 02:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='package',
            table='package',
        ),
    ]
